server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
        routes:
          - id: auth
            uri: lb://auth
            predicates:
              - Path=/auth/**
          - id: news
            uri: lb://news
            predicates:
              - Path=/news/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost